### ISSUE TITLE
Syncdb error when I have two databases

### ISSUE THREAD

**Issue by mpetyx** [scholrly/neo4django#105]
I guess this is a newbie question but I have in the settings.py the two databases,

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3', 
        'NAME': 'bulk.db',  
        'USER': '',  
        'PASSWORD': '',  
        'HOST': '',  
        'PORT': '',  
    }
}

NEO4J_DATABASES = {
    'default' : {
        'HOST':'localhost',
        'PORT':7474,
        'ENDPOINT':'/db/data'
    }
}
 and I have created in the models.py both models for sqlite and neo4j.

When i run the command, python manage.py syncdb, I expect it to create all the tables that are sql depended.
What I get is:
/neo4django/utils.py", line 141, in **getattr**
    return getattr(super(AttrRouter, self), name)
AttributeError: 'super' object has no attribute 'db_type'
Do you have any ideas?

**Comment by mpetyx** [comment]
Somehow it worked, and now all the sql models are in the database.
Now I will try to have both the databases up and running.
I am not sure how I did it, yet :P

**Comment by mhluongo** [comment]
Have you tried the database router that comes with neo4django? https://github.com/scholrly/neo4django#working-alongside-django-orm

Let me know if that helps!

**Comment by mpetyx** [comment]
Thank you very much. I have already this on my settings.py following the README file.
Sometimes it seems like working and some others it just crashes. 
I will work more on it, because it seems like I have something the wrong way.
As soon as I have a more descent answer, I will update the issue here.

**Comment by mhluongo** [comment]
Thanks! And if you have any more info (Neo4j version, Django version, etc) that might help as well. Sorry for the trouble!

**Comment by mhluongo** [comment]
@mpetyx are you still seeing this, or can I close the issue?

**Comment by mpetyx** [comment]
Actually if that's ok with you, I would like to have a few more days.
I am working with django 1.4 and neo4j 1.8.

**Comment by mhluongo** [comment]
Hm, interesting. I doubt this is the problem, but I'm definitely not caught up to Neo4j 1.8- in fact, as of 1.7 many of the query tests break (http://travis-ci.org/#!/scholrly/neo4django/jobs/1624007).

I haven't heard complaints from users about Django 1.4 yet, though we're running 1.3.2 internally.

Anyway, let me know if it crops back up again, and heads up about your Neo4j version.

**Comment by mhluongo** [comment]
I've filed the Neo4j update issue as #110- it'd be an awesome contribution if you get some time! :)

**Comment by mhluongo** [comment]
@mpetyx can you confirm this is still a problem?

**Comment by mpetyx** [comment]
No no it's not a problem, because i downgraded my Neo4j and never actually used again version 1.8 again. ( i have not idea if it is supported at the moment )
thank you very much!

**Comment by mhluongo** [comment]
Great, thanks! When 1.8 general release comes around, I'll be on it :)
